language: go
sudo: false

matrix:
  include:
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: {GO111MODULE: "off"}
    - go: "1.11.x"
      env: {GO111MODULE: "on"}
    - go: "1.12.x"
      env: {GO111MODULE: "off"}
    - go: "1.12.x"
      env: {GO111MODULE: "on"}
    - go: "1.13.x"
      env: {GO111MODULE: "off"}
    - go: "1.13.x"
      env: {GO111MODULE: "on"}
    - go: "1.14.x"
      env: {GO111MODULE: "off"}
    - go: "1.14.x"
      env: {GO111MODULE: "on"}
    - go: "tip"
      env: {GO111MODULE: "off"}
    - go: "tip"
      env: {GO111MODULE: "on"}

install: |
  if test -z "$(go env GOMOD)"; then
    go get -d -t ./... &&
    ver=$(sed -n '/^require/s/.*[ -]//p' go.mod) &&
    (
      cd "$(go env GOPATH)/src/golang.org/x/tools" &&
      git checkout "$ver"
    )
  fi

script:
  - go test -race ./...
